### PR TITLE
Creating tests for report class. It was simpler than I was thinking.

### PR DESCRIPTION
**Pull request by Daibushi**
This is a very short class, than I made only one test. I guess not understand what you need, but tell me case you need more something.

### CODE REVIEW

**Comment by Daibushi** [comment]
I tried to do something, but Alex made better. kkkkkkkkkk

**Comment by eric-kovshovik** [comment]
@Daibushi you did a great job too! Some aspects in my MR still not perfect, because it didn't want to change the controller itself

**Comment by Daibushi** [comment]
Thanks @eric-kovshovik

**Comment by AlexAvlonitis** [comment]
Thanks for the contribution @Daibushi. This has been done by this PR: https://github.com/AlexAvlonitis/kardies/pull/31/files, there are other open issues if you are interested, and will be more in the near future.

Generally for tests you want to aim for the negative and positive results, what happens during the happy path and what happens when errors are raised, like this example -> https://github.com/AlexAvlonitis/kardies/pull/31/files

**Comment by Daibushi** [comment]
@ AlexAvlonitis when I was making the tests I notice that we never can get the negative result because when is puted an invalid parameter always got an : unauthorized response. Because this I guess I really was't testing the controller itself but I was testing the authentication method, that don't allow an inexistent user to create a report. But I needed to test the arguments too. I forgot, kkkkkk. I will try more something. Long live to hacktoberfest.

**Comment by Daibushi** [comment]
@AlexAvlonitis you couldn't mark my PR as invalid. Ok my work will not be merged, but it was not invalid. I tried to make something to contribute. But, it's your project. Good luck.

**Comment by Daibushi** [comment]
@AlexAvlonitis thanks guy. I will study the other issues.

**Pull request closed without merging**
